services:
  bino-bank-mongo-server:
    image: mongo:latest
    container_name: bino-bank-mongo-server
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: u123
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: binoBank
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - ./MongoServersSetup/binoBank.init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      bino-bank-net:
        ipv4_address: 192.168.0.2
  provider-1-mongo-server:
    image: mongo:latest
    container_name: provider-1-mongo-server
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: u456
      MONGO_INITDB_ROOT_PASSWORD: 654321
      MONGO_INITDB_DATABASE: provider1
    ports:
      - 27018:27017
    expose:
      - 27017
    volumes:
      - ./MongoServersSetup/provider1.init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      bino-bank-net:
        ipv4_address: 192.168.0.3
  provider-2-mongo-server:
    image: mongo:latest
    container_name: provider-2-mongo-server
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: uabc
      MONGO_INITDB_ROOT_PASSWORD: 123abc
      MONGO_INITDB_DATABASE: provider2
    ports:
      - 27019:27017
    expose:
      - 27017
    volumes:
      - ./MongoServersSetup/provider2.init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      bino-bank-net:
        ipv4_address: 192.168.0.4
  reconciliation-cron-job:
    build: 
      context: ./
      dockerfile: ./ReconciliationCronJob/Dockerfile.compose
    container_name: reconciliation-cron-job
    restart: always
    command: reconciliation
    networks:
      bino-bank-net:
        ipv4_address: 192.168.0.10
networks:
  bino-bank-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24