services:
  bino-bank-mongo-server:
    image: mongo:latest
    container_name: bino-bank-mongo-server
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: u123
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: binoBank
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - ./MongoServersSetup/binoBank.init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      bino-bank-net:
        ipv4_address: 192.168.0.2
  provider-1-mongo-server:
    image: mongo:latest
    container_name: provider-1-mongo-server
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: u456
      MONGO_INITDB_ROOT_PASSWORD: 654321
      MONGO_INITDB_DATABASE: provider1
    ports:
      - 27018:27017
    expose:
      - 27017
    volumes:
      - ./MongoServersSetup/provider1.init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      bino-bank-net:
        ipv4_address: 192.168.0.3
  provider-2-mongo-server:
    image: mongo:latest
    container_name: provider-2-mongo-server
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: uabc
      MONGO_INITDB_ROOT_PASSWORD: 123abc
      MONGO_INITDB_DATABASE: provider2
    ports:
      - 27019:27017
    expose:
      - 27017
    volumes:
      - ./MongoServersSetup/provider2.init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      bino-bank-net:
        ipv4_address: 192.168.0.4
  reconciliation-cron-job:
    build: 
      context: ./
      dockerfile: ./ReconciliationCronJob/Dockerfile.compose
    container_name: reconciliation-cron-job
    restart: always
    command: reconciliation
    networks:
      bino-bank-net:
        ipv4_address: 192.168.0.5
  provider1-service:
    build: 
      context: ./
      dockerfile: ./ProviderWebhookModule/Dockerfile.compose
    environment:
      PORT: 3000
      HOST: 0.0.0.0
      WEBHOOK_ADDRESS: 192.168.0.1:3000
      DB_CONNECTION_STRING: mongodb://provider1:654321@192.168.0.1:27018/?authSource=provider1&readPreference=primary&ssl=false
      DB_NAME: provider1
    ports:
      - 3001:3000
    container_name: provider1-service
    restart: always
    networks:
      bino-bank-net:
        ipv4_address: 192.168.0.6
  provider2-service:
    build: 
      context: ./
      dockerfile: ./ProviderWebhookModule/Dockerfile.compose
    environment:
      PORT: 3000
      HOST: 0.0.0.0
      WEBHOOK_ADDRESS: 192.168.0.1:3000
      DB_CONNECTION_STRING: mongodb://provider2:123abc@192.168.0.1:27019/?authSource=provider2&readPreference=primary&ssl=false
      DB_NAME: provider2
    ports:
      - 3002:3000
    container_name: provider2-service
    restart: always
    networks:
      bino-bank-net:
        ipv4_address: 192.168.0.7
  bino-bank:
    build: 
      context: ./
      dockerfile: ./BinoBankStatementModule/Dockerfile.compose
    environment:
      PROVIDER_1_ADDRESS: 192.168.0.1:3001
      PROVIDER_2_ADDRESS: 192.168.0.1:3002
    ports:
      - 3000:3000
    container_name: bino-bank
    restart: always
    networks:
      bino-bank-net:
        ipv4_address: 192.168.0.8
networks:
  bino-bank-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24