FROM node:8-alpine

RUN apk update && apk add tzdata &&\ 
    cp /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime &&\ 
    echo "America/Sao_Paulo" > /etc/timezone &&\ 
    apk del tzdata && rm -rf /var/cache/apk/*

RUN mkdir /app
COPY ./BinoBankStatementModule /app
RUN chmod -R +x /app

COPY ./MicroservicesBuildingBlocksLibrary /MicroservicesBuildingBlocksLibrary
COPY ./StatementCoreLibrary /StatementCoreLibrary

WORKDIR /app

RUN npm install

CMD ["npm", "start"]